### ISSUE TITLE
Decomp guide to-do

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#1479]
List of tasks by @thefoxcam 
- [ ] Confirm I didn't make any inaccurate claims, especially for the "types of executables" and "decomp process" section which I kinda just guessed on
- [ ] Should we just list the object file types instead of calling them DLLs?
- [x] Add diagram for decomp process (foxcam)
- [ ] Clarify Melee compiler info, mention patch by Ninji
- [ ] Explain why there are asm/ files in the repo, mention how dtk makes the updated ones when you set up the repo
- [ ] Section in "decomp process" introducing the decompiler/m2c (foxcam)
- [ ] Maybe a page on how to get a TU ready for a PR and what the different tests do?

**Comment by thefoxcam** [comment]
guide moved to https://wiki.decomp.dev/en/resources/decomp-intro-melee

**Comment by ribbanya** [comment]
Does this have Talk pages? Should we still track to-do tasks here?
