### ISSUE TITLE
Replace `TODO` comments with GitHub issues

### ISSUE THREAD

**Issue by ribbanya** [doldecomp/melee#488]
# `dolphin`

### `GXFifo`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/dolphin/gx/GXFifo.c#L133
### `GXLight`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/dolphin/gx/GXLight.c#L3

# `sysdolphin`

### `mtx`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/sysdolphin/baselib/mtx.c#L70
### `shadow`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/sysdolphin/baselib/shadow.c#L38

# `melee`

### `fighter`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L47
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L89
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L123
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L140
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L824
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L1198
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L2222
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L2269
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/fighter.c#L2313
### `ftbosslib`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/ftbosslib.c#L11
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/ftbosslib.c#L36
### `ftdata`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/asm/melee/ft/ftdata.s#L2176
### `chara/ftIceClimber/fticeclimber2_nana`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftIceClimber/fticeclimber2_nana.c#L3
### `chara/ftKirby/ftkirby`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftKirby/ftkirby.c#L3
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftKirby/ftkirby.c#L7
### `chara/ftMasterHand/ftMasterHand_2`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftMasterHand/ftMasterHand_2.c#L104
### `chara/ftMasterHand/ftMasterHand_8`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftMasterHand/ftMasterHand_8.c#L54
### `chara/ftSamus/ftsamus3`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/ft/chara/ftSamus/ftsamus3.c#L142

### `ground`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/gr/ground.c#L428
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/gr/ground.c#L1499

### `mpcoll`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/mp/mpcoll.c#L8
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/mp/mpcoll.c#L103
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/mp/mpcoll.c#L634
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/mp/mpcoll.c#L686
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/mp/mpcoll.c#L745

### `player`
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/pl/player.c#L25
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/pl/player.c#L43
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/pl/player.c#L134
- [ ] https://github.com/doldecomp/melee/blob/346f267c5ae1dbb1f28aee40cedb9360aa033782/src/melee/pl/player.c#L368

**Comment by ribbanya** [comment]
Replaced with Doxygen comments instead.
